sudo: false
language: node_js
os:
  - linux
  - osx
node_js:
  - '8'
  - '9'
  - 'lts/*'
script:
  - npm test
  # - npm run-script test2
  # - npm run-script test3


#cache:
#  directories:
#    - node_modules
