image: Visual Studio 2017
platform: x64
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "MAJOR"

install:
- cmd: npm install

test_script:
- cmd: npm test

build: off
