version: 2.1
orbs :
  node : circleci/node@1.1.6
jobs :
  test :
    executor :
      name : node/default
    steps :
      - checkout
      - node/with-cache:
          steps :
            - run : git config --global user.email "testing@testing.com"
            - run : git config --global user.name "Testing"
            - run : node -v
            - run : npm install
            - run : npm test
workflows :
    test :
      jobs :
        - test
